### ISSUE TITLE
Can't configure with express 4

### ISSUE THREAD

**Issue by santimacia** [othiym23/node-continuation-local-storage#22]
I'm having troubles with configuration under express4. I tried at the beginning and in the end with same result. I followed the instructions of issue #15

 This is the code I tried:

```
app.use(function(req, res, next) {
  ns.bindEmitter(req);
  ns.bindEmitter(res);
  return ns.run(next);

});
app.use(function(req, res) {
  return ns.set('traceId', 'something');


});
app.get('/traced', function(req, res) {
   console.log("traceId = " + (ns.get('traceId')));
   res.send('ok')
});
```

And the stack error:

```
TypeError: Object object has no method 'toString'
    at node_modules/express/lib/application.js:140:28
    at node_modules/express/lib/router/index.js:140:5
    at node_modules/express/lib/router/index.js:265:10
    at next (node_modules/express/lib/router/index.js:165:14)
    at next (node_modules/express/lib/router/index.js:182:38)
    at next (node_modules/express/lib/router/index.js:182:38)
    at next (node_modules/express/lib/router/index.js:182:38)
    at next (node_modules/express/lib/router/index.js:182:38)
    at next (node_modules/express/lib/router/index.js:182:38)
    at next (node_modules/express/lib/router/index.js:182:38)
```

**Comment by antonmos** [comment]
I can confirm that @arthurschreiber's suggestion is correct because this is working fine when using https://github.com/othiym23/cls-middleware

**Comment by ckitt** [comment]
I would like to confirm again that @arthurschreiber solution solve the problem! Thanks.
