### ISSUE TITLE
sporadic errors "Cannot call method 'apply' of undefined" in context.js

### ISSUE THREAD

**Issue by sseide** [othiym23/node-continuation-local-storage#91]
Hello,

first of all - thanks for this module, as thread local storage is much needed for larger apps... My primary use case here is for logging purpose to be able to correlate errors further down the event loop with actual requests. So it's an workaround for missing useful stack traces in node...

That said in my Express app i run into a bug from time to time where the context seems to get lost? I cannot reproduce it savely as it happens only after some time (hours/days?) running without problems. Maybe some of you can spot a hint to dig deeper into the problem.

The problem seems to be related with mysql (but not really shure about that), but every mysql pool created gets covered with cls-mysql before using, e.g.

<pre>
var mysql = require('mysql');
var ns = require('continuation-local-storage').getNamespace('my.namespace');
require('cls-mysql')(ns);
var pool = mysql.createPool({...});
</pre>

The bug presents itself during logging via winston - no real log messages are produced anymore, only the following ones are written to the logfile:

<pre>
TypeError: Cannot call method 'apply' of undefined,
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.<anonymous> (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit._callback (/home/user/node/node_server/node_modules/continuation-local-storage/context.js:84:17),
     at Quit.Sequence.end (/home/user/node/node_server/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24),
     at Protocol.end (/home/user/node/node_server/node_modules/mysql/lib/protocol/Protocol.js:104:24),
     at Socket.<anonymous> (/home/user/node/node_server/node_modules/mysql/lib/Connection.js:115:28),
     at Socket.emit (events.js:117:20),
     at _stream_readable.js:929:16,
     at /home/user/node/node_server/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31,
     at process._tickCallback (node.js:419:13)
</pre>

Sometimes there is no reference to other code than the context.js file at all within the stacktrace.
Some hints or ideas to fix this problem?

I am using 
- express 4.14.0
- continuation-local-storage 3.2.0
- mysql 2.11.1
- cls-mysql 1.0.2 

Thanks in advance,
Stefan

**Comment by bdragos** [comment]
I encountered a similar issue and in my case the code was calling connection.commit() without a callback. Once I added the callback the problem went away. I wonder if the check for undefined was missed or intentionally left out (in Namespace.prototype.bind). 

Hope it helps,
Dragos

**Comment by Qard** [comment]
By the sound of that, it might be a bug in how `cls-mysql` wraps `connection.commit()`.

**Comment by sseide** [comment]
Thanks all  - in the end it was not really mysql (even if it was mentioned in the logs) - it just was triggered in an method calling mysql. Some other EventEmitters where not bound to the namespace.Using this together with logging (Winston here) triggered this error. You must be really carefull to really catch all of them with bindings...
